name: Subgraph Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_conf: |
            keep-env-derivations = true
            keep-outputs = true

      - name: Restore and save Nix store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          gc-max-store-size-linux: 1G

      - run: nix develop -c forge soldeer install
      # See rainix.yaml for why we manually init this submodule.
      - run: git -C dependencies/rain-pyth-0.0.0-git submodule update --init lib/pyth-crosschain
      - run: nix develop -c rainix-sol-prelude

      - name: Install subgraph dependencies
        run: nix develop -c bash -c "cd subgraph && npm install"

      - name: Codegen
        run: nix develop -c bash -c "cd subgraph && npx graph codegen"

      - name: Run matchstick tests
        run: nix develop -c bash -c "cd subgraph && npx graph test -d"
